const fs = require('fs');

fs.writeFileSync('src/types/game.ts', [
'export type Symbol = "A" | "K" | "Q" | "J" | "SPADE" | "HEART" | "CLUB" | "DIAMOND" | "GOLDEN" | "WILD" | "SCATTER";',
'export interface SpinResult {',
'  grid: Symbol[][];',
'  wins: WinResult[];',
'  totalWin: number;',
'  cascades: CascadeResult[];',
'  multiplier: number;',
'  freeSpinsAwarded: number;',
'  isFreeSpinMode: boolean;',
'}',
'export interface WinResult {',
'  symbol: Symbol;',
'  count: number;',
'  positions: number[][];',
'  payout: number;',
'}',
'export interface CascadeResult {',
'  removedPositions: number[][];',
'  newGrid: Symbol[][];',
'  wins: WinResult[];',
'  multiplier: number;',
'}',
'export interface SpinRequest {',
'  userId: string;',
'  betAmount: number;',
'  isFreeSpinMode?: boolean;',
'  freeSpinMultiplier?: number;',
'}'
].join('\n'), 'utf8');

fs.writeFileSync('src/engine/constants.ts', [
'import { Symbol } from "../types/game";',
'export const REELS = 5;',
'export const ROWS = 4;',
'export const SYMBOL_WEIGHTS: Record<Symbol, number> = {',
'  A: 12, K: 12, Q: 14, J: 14,',
'  SPADE: 10, HEART: 10, CLUB: 10, DIAMOND: 10,',
'  GOLDEN: 6, WILD: 4, SCATTER: 3,',
'};',
'export const PAYOUTS: Record<Symbol, number[]> = {',
'  A:       [0, 0, 5,  15,  50],',
'  K:       [0, 0, 5,  15,  50],',
'  Q:       [0, 0, 4,  12,  40],',
'  J:       [0, 0, 4,  12,  40],',
'  SPADE:   [0, 0, 8,  25,  80],',
'  HEART:   [0, 0, 8,  25,  80],',
'  CLUB:    [0, 0, 8,  25,  80],',
'  DIAMOND: [0, 0, 8,  25,  80],',
'  GOLDEN:  [0, 0, 15, 50,  150],',
'  WILD:    [0, 0, 20, 75,  200],',
'  SCATTER: [0, 0, 2,  10,  50],',
'};',
'export const MULTIPLIER_STEPS = [1, 2, 3, 5];',
'export const FREE_SPIN_MULTIPLIER_STEPS = [2, 4, 6, 10];',
'export const SCATTER_TRIGGER_COUNT = 3;',
'export const FREE_SPINS_AWARDED = 10;'
].join('\n'), 'utf8');

fs.writeFileSync('src/engine/ReelGenerator.ts', [
'import { randomBytes } from "crypto";',
'import { Symbol } from "../types/game";',
'import { SYMBOL_WEIGHTS, REELS, ROWS } from "./constants";',
'const SYMBOLS = Object.keys(SYMBOL_WEIGHTS) as Symbol[];',
'const TOTAL_WEIGHT = Object.values(SYMBOL_WEIGHTS).reduce((a, b) => a + b, 0);',
'function secureRandom(): number {',
'  const buf = randomBytes(4);',
'  return buf.readUInt32BE(0) / 0xFFFFFFFF;',
'}',
'function pickSymbol(): Symbol {',
'  let rand = secureRandom() * TOTAL_WEIGHT;',
'  for (const sym of SYMBOLS) {',
'    rand -= SYMBOL_WEIGHTS[sym];',
'    if (rand <= 0) return sym;',
'  }',
'  return SYMBOLS[SYMBOLS.length - 1];',
'}',
'export function generateGrid(): Symbol[][] {',
'  const grid: Symbol[][] = [];',
'  for (let reel = 0; reel < REELS; reel++) {',
'    const col: Symbol[] = [];',
'    for (let row = 0; row < ROWS; row++) col.push(pickSymbol());',
'    grid.push(col);',
'  }',
'  return grid;',
'}'
].join('\n'), 'utf8');

fs.writeFileSync('src/engine/WinCalculator.ts', [
'import { Symbol, WinResult } from "../types/game";',
'import { PAYOUTS, REELS } from "./constants";',
'export function calculateWins(grid: Symbol[][], betAmount: number, multiplier: number): WinResult[] {',
'  const wins: WinResult[] = [];',
'  const symbols = new Set(grid.flat().filter(s => s !== "SCATTER"));',
'  for (const symbol of symbols) {',
'    const target = symbol;',
'    let ways = 1;',
'    let count = 0;',
'    const positions: number[][] = [];',
'    for (let reel = 0; reel < REELS; reel++) {',
'      const matches = grid[reel].map((s, row) => ({ s, row })).filter(({ s }) => s === target || s === "WILD");',
'      if (matches.length === 0) break;',
'      ways *= matches.length;',
'      count++;',
'      matches.forEach(({ row }) => positions.push([reel, row]));',
'    }',
'    if (count >= 3) {',
'      const basePayout = PAYOUTS[symbol]?.[count] ?? 0;',
'      const payout = basePayout * betAmount * ways * multiplier;',
'      if (payout > 0) wins.push({ symbol, count, positions, payout });',
'    }',
'  }',
'  return wins;',
'}'
].join('\n'), 'utf8');

fs.writeFileSync('src/engine/CascadeEngine.ts', [
'import { Symbol, WinResult, CascadeResult } from "../types/game";',
'import { generateGrid } from "./ReelGenerator";',
'import { calculateWins } from "./WinCalculator";',
'import { MULTIPLIER_STEPS, FREE_SPIN_MULTIPLIER_STEPS } from "./constants";',
'function removeWinningSymbols(grid: Symbol[][], wins: WinResult[]): Symbol[][] {',
'  const newGrid = grid.map(col => [...col]) as Symbol[][];',
'  const toRemove = new Set(wins.flatMap(w => w.positions.map(([r, c]) => `${r},${c}`)));',
'  for (const key of toRemove) {',
'    const [reel, row] = key.split(",").map(Number);',
'    newGrid[reel][row] = null as any;',
'  }',
'  for (let reel = 0; reel < newGrid.length; reel++) {',
'    const filled = newGrid[reel].filter(s => s !== null);',
'    const newSymbols = generateGrid()[reel].slice(0, newGrid[reel].length - filled.length);',
'    newGrid[reel] = [...newSymbols, ...filled];',
'  }',
'  return newGrid;',
'}',
'export function runCascades(initialGrid: Symbol[][], betAmount: number, isFreeSpinMode: boolean): CascadeResult[] {',
'  const cascades: CascadeResult[] = [];',
'  const steps = isFreeSpinMode ? FREE_SPIN_MULTIPLIER_STEPS : MULTIPLIER_STEPS;',
'  let currentGrid = initialGrid;',
'  let cascadeCount = 0;',
'  while (true) {',
'    const multiplier = steps[Math.min(cascadeCount, steps.length - 1)];',
'    const wins = calculateWins(currentGrid, betAmount, multiplier);',
'    if (wins.length === 0) break;',
'    const removedPositions = wins.flatMap(w => w.positions);',
'    const newGrid = removeWinningSymbols(currentGrid, wins);',
'    cascades.push({ removedPositions, newGrid, wins, multiplier });',
'    currentGrid = newGrid;',
'    cascadeCount++;',
'  }',
'  return cascades;',
'}'
].join('\n'), 'utf8');

fs.writeFileSync('src/engine/SuperAceGame.ts', [
'import { SpinRequest, SpinResult, Symbol } from "../types/game";',
'import { generateGrid } from "./ReelGenerator";',
'import { calculateWins } from "./WinCalculator";',
'import { runCascades } from "./CascadeEngine";',
'import { SCATTER_TRIGGER_COUNT, FREE_SPINS_AWARDED, MULTIPLIER_STEPS, FREE_SPIN_MULTIPLIER_STEPS } from "./constants";',
'function countScatters(grid: Symbol[][]): number {',
'  return grid.flat().filter(s => s === "SCATTER").length;',
'}',
'export function spin(req: SpinRequest): SpinResult {',
'  const { betAmount, isFreeSpinMode = false, freeSpinMultiplier = 1 } = req;',
'  const steps = isFreeSpinMode ? FREE_SPIN_MULTIPLIER_STEPS : MULTIPLIER_STEPS;',
'  const grid = generateGrid();',
'  const initialMultiplier = isFreeSpinMode ? freeSpinMultiplier : steps[0];',
'  const initialWins = calculateWins(grid, betAmount, initialMultiplier);',
'  const cascades = runCascades(grid, betAmount, isFreeSpinMode);',
'  const cascadeWin = cascades.reduce((sum, c) => sum + c.wins.reduce((s, w) => s + w.payout, 0), 0);',
'  const initialWin = initialWins.reduce((sum, w) => sum + w.payout, 0);',
'  const totalWin = initialWin + cascadeWin;',
'  const multiplier = cascades.length > 0 ? cascades[cascades.length - 1].multiplier : initialMultiplier;',
'  const scatterCount = countScatters(grid);',
'  const freeSpinsAwarded = scatterCount >= SCATTER_TRIGGER_COUNT ? FREE_SPINS_AWARDED : 0;',
'  return { grid, wins: initialWins, totalWin, cascades, multiplier, freeSpinsAwarded, isFreeSpinMode };',
'}'
].join('\n'), 'utf8');

fs.writeFileSync('src/routes/game.routes.ts', [
'import { Router, Request, Response } from "express";',
'import { spin } from "../engine/SuperAceGame";',
'const router = Router();',
'router.post("/spin", (req: Request, res: Response) => {',
'  try {',
'    const { userId, betAmount, isFreeSpinMode, freeSpinMultiplier } = req.body;',
'    if (!userId || !betAmount || betAmount <= 0) return res.status(400).json({ error: "Invalid spin request" });',
'    const result = spin({ userId, betAmount, isFreeSpinMode, freeSpinMultiplier });',
'    res.json({ success: true, result });',
'  } catch (err: any) {',
'    res.status(500).json({ error: err.message });',
'  }',
'});',
'router.get("/config", (_req: Request, res: Response) => {',
'  res.json({ reels: 5, rows: 4, ways: 1024, minBet: 0.1, maxBet: 1000, rtp: 97 });',
'});',
'export default router;'
].join('\n'), 'utf8');

fs.writeFileSync('src/index.ts', [
'import express from "express";',
'import cors from "cors";',
'import helmet from "helmet";',
'import gameRoutes from "./routes/game.routes";',
'const app = express();',
'const PORT = process.env.GAME_ENGINE_PORT || 3002;',
'app.use(helmet());',
'app.use(cors());',
'app.use(express.json());',
'app.use("/api/game", gameRoutes);',
'app.get("/health", (_req, res) => {',
'  res.json({ status: "ok", service: "game-engine", timestamp: new Date() });',
'});',
'app.listen(PORT, () => console.log(`✅ Game Engine running on port ${PORT}`));',
'export default app;'
].join('\n'), 'utf8');

console.log('All files written successfully!');