import crypto from "crypto";

export interface ProvablyFairParams {
  serverSeed: string;      // Generated by server, hashed and shown before spin
  clientSeed: string;      // Provided by player (or their browser)
  nonce: number;           // Incrementing counter per spin
  cursor: number;          // Position in byte stream for multi-reel
}

export function generateServerSeed(): string {
  return crypto.randomBytes(32).toString("hex");
}

export function hashServerSeed(seed: string): string {
  return crypto.createHash("sha256").update(seed).digest("hex");
}

export function generateRandomNumber(params: ProvablyFairParams): number {
  const { serverSeed, clientSeed, nonce, cursor } = params;
  
  // HMAC-SHA256(serverSeed, clientSeed:nonce:cursor)
  const message = `${clientSeed}:${nonce}:${cursor}`;
  const hmac = crypto.createHmac("sha256", serverSeed).update(message).digest("hex");
  
  // Convert first 8 hex chars to decimal (0-4294967295)
  const decimal = parseInt(hmac.substring(0, 8), 16);
  
  // Normalize to 0-1 range
  return decimal / 0xFFFFFFFF;
}

export function generateReelStop(params: ProvablyFairParams, reelLength: number): number {
  const random = generateRandomNumber(params);
  return Math.floor(random * reelLength);
}

export function verifySpin(
  serverSeed: string,
  clientSeed: string,
  nonce: number,
  reelLengths: number[]
): number[] {
  // Player can call this to verify the server didn't cheat
  return reelLengths.map((length, cursor) => {
    const params: ProvablyFairParams = { serverSeed, clientSeed, nonce, cursor };
    return generateReelStop(params, length);
  });
}
