const fs = require('fs');
const schema = [
'generator client {',
'  provider = "prisma-client-js"',
'}',
'',
'datasource db {',
'  provider = "postgresql"',
'  url      = env("DATABASE_URL")',
'}',
'',
'model User {',
'  id           String    @id @default(uuid())',
'  username     String    @unique',
'  email        String    @unique',
'  passwordHash String',
'  role         Role      @default(PLAYER)',
'  isActive     Boolean   @default(true)',
'  isVerified   Boolean   @default(false)',
'  createdAt    DateTime  @default(now())',
'  updatedAt    DateTime  @updatedAt',
'  wallet       Wallet?',
'  sessions     Session[]',
'  @@map("users")',
'}',
'',
'model Wallet {',
'  id        String   @id @default(uuid())',
'  userId    String   @unique',
'  balance   Decimal  @default(0) @db.Decimal(18, 8)',
'  currency  String   @default("USDT")',
'  createdAt DateTime @default(now())',
'  updatedAt DateTime @updatedAt',
'  user      User     @relation(fields: [userId], references: [id])',
'  @@map("wallets")',
'}',
'',
'model Session {',
'  id        String   @id @default(uuid())',
'  userId    String',
'  token     String   @unique',
'  ipAddress String?',
'  userAgent String?',
'  expiresAt DateTime',
'  createdAt DateTime @default(now())',
'  user      User     @relation(fields: [userId], references: [id])',
'  @@map("sessions")',
'}',
'',
'enum Role {',
'  PLAYER',
'  ADMIN',
'  SUPER_ADMIN',
'}'
].join('\n');

fs.writeFileSync('prisma/schema.prisma', schema, 'utf8');
const buf = fs.readFileSync('prisma/schema.prisma');
console.log('First byte:', buf[0], '(must be 103)');
console.log('Done!');